# Camera Calibration

Intrinsic matrix = [[fx,0,cx],[0,fy,cy],[0,0,1]]
(fx,fy) - focal length
(cx,cy) - principal points
camera extrinsic - [R/t]
k.[R/t] [x,y,z,1] = s [x,y,1]

steps
1. Take multiple images
2. Define 3D coordinates of checker board corners (size: 9*6)
3. each image detect 2D coordinateds of corners : findcheckerboardcorners()
4. Match 3D and 2D points
   estimate parameters cv2.calibrateCamera()

# Experiment 4

Perform camera calibration and find internsic and externsic parameters

In [10]:
import cv2
import numpy as np
import os
import glob

In [18]:

# 1. Define the dimensions of checkerboard
CHECKERBOARD = (9, 6)  # (columns, rows) of inner corners

# 2. Create arrays to store object points and image points
objpoints = []  # 3D points in real world
imgpoints = []  # 2D points in image plane

# 3. Define real world coordinates for 3D points
# Assuming square size = 1 unit (can be mm, cm etc.)
objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)

In [19]:
# 4. Load all checkerboard images
images = glob.glob('checker/*.jpg')  # or .png, adjust as needed

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 5. Find the checkerboard corners
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)

    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Optional: Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners, ret)
        cv2.imshow('Corners', img)
        cv2.waitKey(0)

cv2.destroyAllWindows()

In [16]:
# 6. Calibrate the camera
ret, camera_matrix, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(
    objpoints, imgpoints, gray.shape[::-1], None, None
)

# 7. Print the results
print("\n=== Calibration Results ===")
print("Camera Matrix (Intrinsic Parameters):\n", camera_matrix)
print("\nDistortion Coefficients:\n", dist_coeffs)


=== Calibration Results ===
Camera Matrix (Intrinsic Parameters):
 [[532.34478614   0.         342.88971564]
 [  0.         532.51305791 236.6224121 ]
 [  0.           0.           1.        ]]

Distortion Coefficients:
 [[-2.85877475e-01  3.33818422e-02  1.26372803e-03 -1.63447106e-04
   1.61320766e-01]]


In [17]:
print("\nExtrinsic Parameters (Rotation and Translation per image):")
for i in range(len(rvecs)):
    print(f"\nImage {i+1}:")
    print("Rotation Vector:\n", rvecs[i])
    print("Translation Vector:\n", tvecs[i])


Extrinsic Parameters (Rotation and Translation per image):

Image 1:
Rotation Vector:
 [[0.16943734]
 [0.27342196]
 [0.01377817]]
Translation Vector:
 [[-3.0269475 ]
 [-4.3890112 ]
 [15.86910128]]

Image 2:
Rotation Vector:
 [[-0.41818527]
 [-0.5007578 ]
 [ 1.33496383]]
Translation Vector:
 [[ 1.86072601]
 [-4.46606658]
 [13.43219859]]

Image 3:
Rotation Vector:
 [[-0.23835105]
 [ 0.34363407]
 [ 1.53101918]]
Translation Vector:
 [[ 2.01448519]
 [-4.12952761]
 [12.7991607 ]]

Image 4:
Rotation Vector:
 [[ 0.42211675]
 [ 0.6575485 ]
 [-1.33505449]]
Translation Vector:
 [[-2.35074767]
 [ 3.26077968]
 [14.10137711]]

Image 5:
Rotation Vector:
 [[-0.2751365 ]
 [ 0.18598453]
 [ 0.35471567]]
Translation Vector:
 [[-1.60923565]
 [-4.03989486]
 [12.63355248]]

Image 6:
Rotation Vector:
 [[-0.10885827]
 [ 0.23663705]
 [-0.00176671]]
Translation Vector:
 [[-3.95248156]
 [-2.72032041]
 [13.130451  ]]

Image 7:
Rotation Vector:
 [[-0.29180937]
 [ 0.42696065]
 [ 1.31315461]]
Translation Vector:
 [[